name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npx honkit build . docs

#      - name: Deploy
#        uses: crazy-max/ghaction-github-pages@v4
#        with:
#          target_branch: gh-pages
#          keep_history: true
#          allow_empty_commit: true
#          build_dir: docs
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #destination_dir: documentation
          publish_dir: ./docs
          allow_empty_commit: true

